sudo: required
language: generic

services:
  - docker
  
before_install:
  - docker build -t michaelramer/react-test -f ./client/Dockerfile.dev ./client
  
script:
#  - docker run michaelramer/react-test npm test -- --coverage
   - docker run -e CI=true michaelramer/react-test npm test
after_success:
  - docker build -t michaelramer/multi-client ./client
  - docker build -t michaelramer/multi-nginx ./nginx
  - docker build -t michaelramer/multi-server ./server
  - docker build -t michaelramer/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push michaelramer/multi-client
  - docker push michaelramer/multi-nginx
  - docker push michaelramer/multi-server
  - docker push michaelramer/multi-worker
  
